[build]
builder = "NIXPACKS"
buildCommand = "npm install && npx prisma generate && npx prisma db push --accept-data-loss"

[deploy]
startCommand = "npx tsx src/server.ts"
healthcheckPath = "/health"
restartPolicyType = "ON_FAILURE"
healthcheckTimeout = 60
