[build]
builder = "NIXPACKS"
buildCommand = "npm install && npx prisma generate && npx tsc -p tsconfig.build.json && npx tsc-alias -p tsconfig.build.json"

[deploy]
startCommand = "npm start"
healthcheckPath = "/api/auctions"
restartPolicyType = "ON_FAILURE"
